### ISSUE TITLE
checklist for additional features to cover  in test set

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/test-models#29]
These were notes made while working on #22 .

- [ ] Make sure selectivity time block captured in test set? (already have q time blocks tho)
- [ ] Make sure -year and -fleet values are included in datasets.
- [ ] make sure lambdas used.
- [ ] Add catch multiplier to one of the test set.
- [ ] All prior types used in the test set.
